# This is a basic workflow to help you get started with Actions

name: CI to deply first surge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the session1-surge branch
on:
  push:
    branches: [ session1-surge ] 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install surge
        run: npm install -g surge
        working-directory: session1-surge/
      
      - name: deploy on surge
        run: surge ./ bilalmk/bootcamp2020 --token "0d686fb82509b5bb279a17e244eab390"
        working-directory: session1-surge/
